package pojo;
// Generated 12-may-2012 18:09:50 by Hibernate Tools 3.2.1.GA

/**
 * Alokairua generated by hbm2java
 */
public class Alokairua  implements java.io.Serializable {


     private String bezeroId;
     private Instalazioa instalazioa;
     private String dataOrdua;
     private String oharra;

    public Alokairua() {
    }

	
    public Alokairua(String bezeroId, Instalazioa instalazioa, String dataOrdua) {
        this.bezeroId = bezeroId;
        this.instalazioa = instalazioa;
        this.dataOrdua = dataOrdua;
    }
    public Alokairua(String bezeroId, Instalazioa instalazioa, String dataOrdua, String oharra) {
       this.bezeroId = bezeroId;
       this.instalazioa = instalazioa;
       this.dataOrdua = dataOrdua;
       this.oharra = oharra;
    }
   
    public String getBezeroId() {
        return this.bezeroId;
    }
    
    public void setBezeroId(String bezeroId) {
        this.bezeroId = bezeroId;
    }

    public Instalazioa getInstalazioa() {
        return this.instalazioa;
    }
    
    public void setInstalazioa(Instalazioa instalazioa) {
        this.instalazioa = instalazioa;
    }
    public String getDataOrdua() {
        return this.dataOrdua;
    }
    
    public void setDataOrdua(String dataOrdua) {
        this.dataOrdua = dataOrdua;
    }
    public String getOharra() {
        return this.oharra;
    }
    
    public void setOharra(String oharra) {
        this.oharra = oharra;
    }




}


