package pojo;
// Generated 08-may-2012 17:22:28 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Kurtsoa generated by hbm2java
 */
public class Kurtsoa  implements java.io.Serializable {


     private Integer id;
     private Monitorea monitorea;
     private Espezialitatea espezialitatea;
     private String izena;
     private String deskribapena;
     private int bezMax;
     private Date data;
     private Set<Ordutegia> ordutegias = new HashSet<Ordutegia>(0);
     private Set<Bezeroa> bezeroas = new HashSet<Bezeroa>(0);

    public Kurtsoa() {
    }

	
    public Kurtsoa(Monitorea monitorea, Espezialitatea espezialitatea, String izena, String deskribapena, int bezMax, Date data) {
        this.monitorea = monitorea;
        this.espezialitatea = espezialitatea;
        this.izena = izena;
        this.deskribapena = deskribapena;
        this.bezMax = bezMax;
        this.data = data;
    }
    public Kurtsoa(Monitorea monitorea, Espezialitatea espezialitatea, String izena, String deskribapena, int bezMax, Date data, Set<Ordutegia> ordutegias, Set<Bezeroa> bezeroas) {
       this.monitorea = monitorea;
       this.espezialitatea = espezialitatea;
       this.izena = izena;
       this.deskribapena = deskribapena;
       this.bezMax = bezMax;
       this.data = data;
       this.ordutegias = ordutegias;
       this.bezeroas = bezeroas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Monitorea getMonitorea() {
        return this.monitorea;
    }
    
    public void setMonitorea(Monitorea monitorea) {
        this.monitorea = monitorea;
    }
    public Espezialitatea getEspezialitatea() {
        return this.espezialitatea;
    }
    
    public void setEspezialitatea(Espezialitatea espezialitatea) {
        this.espezialitatea = espezialitatea;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getDeskribapena() {
        return this.deskribapena;
    }
    
    public void setDeskribapena(String deskribapena) {
        this.deskribapena = deskribapena;
    }
    public int getBezMax() {
        return this.bezMax;
    }
    
    public void setBezMax(int bezMax) {
        this.bezMax = bezMax;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set<Ordutegia> getOrdutegias() {
        return this.ordutegias;
    }
    
    public void setOrdutegias(Set<Ordutegia> ordutegias) {
        this.ordutegias = ordutegias;
    }
    public Set<Bezeroa> getBezeroas() {
        return this.bezeroas;
    }
    
    public void setBezeroas(Set<Bezeroa> bezeroas) {
        this.bezeroas = bezeroas;
    }




}


