package pojo;
// Generated 12-may-2012 18:09:50 by Hibernate Tools 3.2.1.GA



/**
 * Administratzailea generated by hbm2java
 */
public class Administratzailea  implements java.io.Serializable {


     private Integer id;
     private String izena;
     private String pasahitza;

    public Administratzailea() {
    }

    public Administratzailea(String izena, String pasahitza) {
       this.izena = izena;
       this.pasahitza = pasahitza;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getPasahitza() {
        return this.pasahitza;
    }
    
    public void setPasahitza(String pasahitza) {
        this.pasahitza = pasahitza;
    }




}


