package pojo;
// Generated 12-may-2012 18:09:50 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Alokairua generated by hbm2java
 */
public class Alokairua  implements java.io.Serializable {


     private String bezeroId;
     private Bezeroa bezeroa;
     private Instalazioa instalazioa;
     private Date dataOrdua;
     private String oharra;

    public Alokairua() {
    }

	
    public Alokairua(String bezeroId, Bezeroa bezeroa, Instalazioa instalazioa, Date dataOrdua) {
        this.bezeroId = bezeroId;
        this.bezeroa = bezeroa;
        this.instalazioa = instalazioa;
        this.dataOrdua = dataOrdua;
    }
    public Alokairua(String bezeroId, Bezeroa bezeroa, Instalazioa instalazioa, Date dataOrdua, String oharra) {
       this.bezeroId = bezeroId;
       this.bezeroa = bezeroa;
       this.instalazioa = instalazioa;
       this.dataOrdua = dataOrdua;
       this.oharra = oharra;
    }
   
    public String getBezeroId() {
        return this.bezeroId;
    }
    
    public void setBezeroId(String bezeroId) {
        this.bezeroId = bezeroId;
    }
    public Bezeroa getBezeroa() {
        return this.bezeroa;
    }
    
    public void setBezeroa(Bezeroa bezeroa) {
        this.bezeroa = bezeroa;
    }
    public Instalazioa getInstalazioa() {
        return this.instalazioa;
    }
    
    public void setInstalazioa(Instalazioa instalazioa) {
        this.instalazioa = instalazioa;
    }
    public Date getDataOrdua() {
        return this.dataOrdua;
    }
    
    public void setDataOrdua(Date dataOrdua) {
        this.dataOrdua = dataOrdua;
    }
    public String getOharra() {
        return this.oharra;
    }
    
    public void setOharra(String oharra) {
        this.oharra = oharra;
    }




}


