package pojo;
// Generated 24-abr-2012 12:01:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Espezialitatea generated by hbm2java
 */
public class Espezialitatea  implements java.io.Serializable {


     private Integer id;
     private String izena;
     private String espezialitatea;
     private Set<Kurtsoa> kurtsoas = new HashSet<Kurtsoa>(0);
     private Set<Monitorea> monitoreas = new HashSet<Monitorea>(0);

    public Espezialitatea() {
    }

	
    public Espezialitatea(String izena) {
        this.izena = izena;
    }
    public Espezialitatea(String izena, String espezialitatea, Set<Kurtsoa> kurtsoas, Set<Monitorea> monitoreas) {
       this.izena = izena;
       this.espezialitatea = espezialitatea;
       this.kurtsoas = kurtsoas;
       this.monitoreas = monitoreas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getEspezialitatea() {
        return this.espezialitatea;
    }
    
    public void setEspezialitatea(String espezialitatea) {
        this.espezialitatea = espezialitatea;
    }
    public Set<Kurtsoa> getKurtsoas() {
        return this.kurtsoas;
    }
    
    public void setKurtsoas(Set<Kurtsoa> kurtsoas) {
        this.kurtsoas = kurtsoas;
    }
    public Set<Monitorea> getMonitoreas() {
        return this.monitoreas;
    }
    
    public void setMonitoreas(Set<Monitorea> monitoreas) {
        this.monitoreas = monitoreas;
    }




}


