package pojo;
// Generated 12-may-2012 18:09:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Instalazioa generated by hbm2java
 */
public class Instalazioa  implements java.io.Serializable {


     private Integer id;
     private String izena;
     private String deskribapena;
     private Set<Alokairua> alokairuas = new HashSet<Alokairua>(0);

    public Instalazioa() {
    }

	
    public Instalazioa(String izena) {
        this.izena = izena;
    }
    public Instalazioa(String izena, String deskribapena, Set<Alokairua> alokairuas) {
       this.izena = izena;
       this.deskribapena = deskribapena;
       this.alokairuas = alokairuas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getDeskribapena() {
        return this.deskribapena;
    }
    
    public void setDeskribapena(String deskribapena) {
        this.deskribapena = deskribapena;
    }
    public Set<Alokairua> getAlokairuas() {
        return this.alokairuas;
    }
    
    public void setAlokairuas(Set<Alokairua> alokairuas) {
        this.alokairuas = alokairuas;
    }




}


