package pojo;
// Generated 24-abr-2012 12:01:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ordutegia generated by hbm2java
 */
public class Ordutegia  implements java.io.Serializable {


     private Integer id;
     private String egunak;
     private String orduTartea;
     private Set<Kurtsoa> kurtsoas = new HashSet<Kurtsoa>(0);

    public Ordutegia() {
    }

    public Ordutegia(String egunak, String orduTartea, Set<Kurtsoa> kurtsoas) {
       this.egunak = egunak;
       this.orduTartea = orduTartea;
       this.kurtsoas = kurtsoas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEgunak() {
        return this.egunak;
    }
    
    public void setEgunak(String egunak) {
        this.egunak = egunak;
    }
    public String getOrduTartea() {
        return this.orduTartea;
    }
    
    public void setOrduTartea(String orduTartea) {
        this.orduTartea = orduTartea;
    }
    public Set<Kurtsoa> getKurtsoas() {
        return this.kurtsoas;
    }
    
    public void setKurtsoas(Set<Kurtsoa> kurtsoas) {
        this.kurtsoas = kurtsoas;
    }




}


